[package]
name = "espforge_platform"
version = "0.1.0"
edition = "2024"
description = "Platform abstractions for espforge projects"
license = "MIT"

[dependencies]
esp-hal = { version = "1.0.0", features = ["esp32c3", "log-04", "unstable"] }


esp-bootloader-esp-idf = { version = "0.4.0", features = ["esp32c3", "log-04"] }
log                    = "0.4.27"

critical-section = "1.2.0"
esp-alloc = "0.9.0"
esp-backtrace = { version = "0.18.1", features = [
  "esp32c3",
  "panic-handler",
  "println",
] }
esp-println = { version = "0.16.1", features = ["esp32c3", "log-04"] }


[profile.dev]
opt-level = "s"

[profile.release]
codegen-units    = 1     
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
