[package]
name = "espforge_platform"
version = "0.1.0"
edition = "2024"
description = "Platform abstractions for espforge projects"
license = "MIT"

[dependencies]
include_dir = { version = "0.7.4", features = ["glob"] }

