[package]
name = "espforge_common"
version = "0.1.0"
edition = "2024"
description = "Configuration model for espforge"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

